### ISSUE TITLE
Hang up when printing over 128 chars to console, power up without connecting a USB host

### ISSUE THREAD

**Issue by ohsawa** [open-degu/degu#6]
**Describe the bug**
Degu hanup after printing 128 characters to console.

**To Reproduce**
1. Update main.py  like following 
```
while True:
       print("")
```
2. Disconnect USB
3. Connect battery CON12
4. Degu hanguped

**Expected behavior**
Run continuously everything without a USB host.

**Version(please complete the following information):**
 - DeguFirmware: 0.9.1

**Comment by takumiando** [comment]
This bug includes not only `print()` in MicroPython but 'printf()' in `modzcoap.c` .
These `printf()` should be error printing of MicroPython.

**Comment by takumiando** [comment]
This bug is fixed in Degu v0.9.2 .
